
import javax.swing.JPanel;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType0Font;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author omera
 */
public class antrenorProgram extends javax.swing.JFrame {

    /**
     * Creates new form antrenorProgram
     */
    public antrenorProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ders Programı \n");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Oluşturma Ekranı");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-print-25.png"))); // NOI18N
        jButton1.setText("Yazdır");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, 24));

        jLabel7.setText("1. Gün");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 82, -1));

        jLabel8.setText("2. Gün");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 82, -1));

        jLabel9.setText("3. Gün");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 82, -1));

        jLabel10.setText("4. Gün");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 82, -1));

        jLabel11.setText("5. Gün");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 82, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tüm vücut", "Kardiyo", "İtiş", "Çekiş", "Sırt", "Göğüs", "Kol", "Omuz", "Bacak", "Boş" }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 105, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tüm vücut", "Kardiyo", "İtiş", "Çekiş", "Sırt", "Göğüs", "Kol", "Omuz", "Bacak", "Boş" }));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 105, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tüm vücut", "Kardiyo", "İtiş", "Çekiş", "Sırt", "Göğüs", "Kol", "Omuz", "Bacak", "Boş" }));
        jPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 105, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tüm vücut", "Kardiyo", "İtiş", "Çekiş", "Sırt", "Göğüs", "Kol", "Omuz", "Bacak", "Boş" }));
        jPanel3.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 105, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tüm vücut", "Kardiyo", "İtiş", "Çekiş", "Sırt", "Göğüs", "Kol", "Omuz", "Bacak", "Boş" }));
        jPanel3.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 105, -1));

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-home-page-24.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 40, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("BMI Hesaplama");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel4.setText("Boy");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 123, -1));

        jTextField1.setOpaque(true);
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 103, -1));

        jLabel5.setText("Kilo");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 123, -1));

        jTextField2.setOpaque(true);
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 103, -1));

        jLabel6.setText("Cinsiyet");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 64, -1));

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton1.setText("Erkek");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton2.setText("Kadın");
        jPanel3.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton2.setText("Hesapla");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel12.setText("Vücut kütle İndeksini(BMI) ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 20));

        jLabel13.setText("Hesapladıktan sonra Programı Oluşturabilirsiniz.");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 280, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        float boy = Float.parseFloat(jTextField1.getText());
        int kilo = Integer.parseInt(jTextField2.getText());
        float kvi = kilo / (boy*boy);
        if(kvi<18.5){
            JOptionPane.showMessageDialog(null, "BMI = " + kvi + "\nİdeal kilonun altında");
        }else if(18.5 <=kvi && kvi <= 24.9 ){
            JOptionPane.showMessageDialog(null, "BMI = " + kvi + "\nİdeal kiloda");
        }else if(25 <=kvi && kvi <= 29.9 ){
            JOptionPane.showMessageDialog(null, "BMI = " + kvi + "\nİdeal kilonun üstünde");
        }else if(30 <=kvi && kvi <= 39.9 ){
            JOptionPane.showMessageDialog(null, "BMI = " + kvi + "\nİdeal kilonun çok üstünde (obez)");
        }else if(40 <=kvi){
            JOptionPane.showMessageDialog(null, "BMI = " + kvi + "\n İdeal kilonun çok üstünde (morbid obez)");
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        createPDF();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        setVisible(false); //ilk paneli gizle
        antrenorUI frame2 = new antrenorUI();
        frame2.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        resetColor(jPanel4);    // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        setColor(jPanel4);    // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseEntered
        public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(197,197,197));
    }
    public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(240,240,240));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(antrenorProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(antrenorProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(antrenorProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(antrenorProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new antrenorProgram().setVisible(true);
            }
        });
    }
   public void createPDF() {
    String birinci = jComboBox1.getSelectedItem().toString();
    String ikinci = jComboBox2.getSelectedItem().toString();
    String ucuncu = jComboBox3.getSelectedItem().toString();
    String dorduncu = jComboBox4.getSelectedItem().toString();
    String besinci = jComboBox5.getSelectedItem().toString();
    

    birinci = movements(birinci);
    ikinci = movements(ikinci);
    ucuncu = movements(ucuncu);
    dorduncu = movements(dorduncu);
    besinci = movements(besinci);
    
    String[] paragraphs1 = birinci.split("\n");
    String[] paragraphs2 = ikinci.split("\n");
    String[] paragraphs3 = ucuncu.split("\n");
    String[] paragraphs4 = dorduncu.split("\n");
    String[] paragraphs5 = besinci.split("\n");
    float y = 800; // Y koordinatını başlangıç değeri olarak belirleyin
    try {
        // Yeni bir PDF belgesi oluştur
        PDDocument document = new PDDocument();

        // Yeni bir sayfa oluştur
        PDPage page = new PDPage(PDRectangle.A4);
        document.addPage(page);

        // Sayfa içeriği için bir PDPageContentStream oluştur
        PDPageContentStream contentStream = new PDPageContentStream(document, page);

        // Font dosyasını yükleyin
        PDType0Font font = PDType0Font.load(document, new File("C:\\Users\\MÜDAFERKAYMAK\\Desktop\\Kcontrol\\Helvetica.ttf"));

        // Metni belgeye ekle
        contentStream.setFont(font, 12);
        contentStream.beginText();
        contentStream.newLineAtOffset(25, 800);

        // Metni paragraf biçimlendirmesiyle ekle
        contentStream.setLeading(14.5f);
       
        for (String paragraph : paragraphs1) {
               contentStream.showText(paragraph);
               contentStream.newLineAtOffset(0, -14.5f); // Y koordinatını düşürerek yeni satıra geç
            }
        for (String paragraph : paragraphs2) {
            contentStream.showText(paragraph);
            contentStream.newLineAtOffset(0, -14.5f); // Y koordinatını düşürerek yeni satıra geç
        }
        for (String paragraph : paragraphs3) {
            contentStream.showText(paragraph);
            contentStream.newLineAtOffset(0, -14.5f); // Y koordinatını düşürerek yeni satıra geç
        }
        for (String paragraph : paragraphs4) {
            contentStream.showText(paragraph);
            contentStream.newLineAtOffset(0, -14.5f); // Y koordinatını düşürerek yeni satıra geç
        }
        for (String paragraph : paragraphs5) {
            contentStream.showText(paragraph);
            contentStream.newLineAtOffset(0, -14.5f); // Y koordinatını düşürerek yeni satıra geç
        }
        contentStream.endText();

        // İçerik akışını kapat
        contentStream.close();

        // PDF belgesini kaydet
        document.save(new File("MMMOOO.pdf"));

        // PDF belgesini kapat
        document.close();

        System.out.println("PDF dosyası oluşturuldu.");
    } catch (IOException e) {
        e.printStackTrace();
    }
}

public String movements(String day) {
    String message = "";

    switch (day) {
        case "İtiş" -> {
            message = "\n\n İtiş Günü\n\n"
                    + " - Bench Press (3 set 5-7 tekrar)\n"
                    + " - Seated Dumbbell Shoulder Press (3 set 6-8 tekrar)\n"
                    + " - Incline Dumbbell Press (3 set 8-10 tekrar)\n"
                    + " - Side Lateral Raise (2 set 10-12 tekrar)\n"
                    + " - Triceps Pressdown (2 set 8-10 tekrar)\n"
                    + " - Overhead Triceps Extension (2 set 8-10 tekrar)";
        }
        case "Çekiş" -> {
            message = "\n\n Çekiş Günü\n\n"
                    + " - Bent-over Row (3 set 5-7 tekrar)\n"
                    + " - Pull Up (3 set 6-8 tekrar)\n"
                    + " - Barbell Shrug (3 set 8-10 tekrar)\n"
                    + " - Face Pull (2 set 10-12 tekrar)\n"
                    + " - Barbell Curl (2 set 8-10 tekrar)\n"
                    + " - Dumbbell Hammer Curl (2 set 8-10 tekrar)";
        }
        case "Kardiyo" -> {
            message = "\n\n Kardiyo Günü\n\n"
                    + " - Burpees\n"
                    + " - Manmakers\n"
                    + " - High Knees\n"
                    + " - Mountain Climbers\n"
                    + " - Lunge Jump\n"
                    + " - Squat Jump";
        }
        case "Sırt" -> {
            message = "\n\n Sırt Günü\n\n"
                    + " - Genis Tutus Barfiks (4 set 15 tekrar)\n"
                    + " - Lat Pulldown (4 set 12-15 tekrar)\n"
                    + " - Cable Rope Row (4 set 20 tekrar)\n"
                    + " - Ters Tutus Barbell Row ( 4 set 10-15 tekrar)";
        }
        case "Göğüs" -> {
            message = "\n\n Göğüs Günü\n\n"
                    + " - Bench Press (4 set 10 tekrar)\n"
                    + " - Dumbell Press (4 set 8 tekrar)\n"
                    + " - İncline Bench Cable Fly (3 set 12-15 tekrar)\n"
                    + " - Cable Crossover ( 3 set 10-12 tekrar)";
        }
        case "Kol" -> {
            message = "\n\n Kol Günü\n\n"
                    + " - Triangle push up (3 set 10-12 tekrar)\n"
                    + " - Hammer Curls (4 set 10-12 tekrar)\n"
                    + " - Cable Curl (3 set 12 tekrar)\n"
                    + " - Dumbell Curl (3 set 10 tekrar)\n"
                    + " - Rope Pushdown (3 set 12 tekrar)";
        }
        case "Omuz" -> {
            message = "\n\n Omuz Günü\n\n"
                    + " - Dumbbell Lateral Raise (4 set 10 tekrar)\n"
                    + " - Facepull (4 set 10 tekrar)\n"
                    + " - Dumbell Shoulder Press (4 set 10 tekrar)\n"
                    + " - Dumbbell Front Raise (4 set 10 tekrar)";
        }
        case "Bacak" -> {
            message = "\n\n Bacak Günü\n\n"
                    + " - Squat (3 set 6-8 tekrar)\n"
                    + " - Romanian Deadlift (2 set 8-10 tekrar)\n"
                    + " - Leg Press (2 set 10-12 tekrar)\n"
                    + " - Leg Curl (2 set 10-12 tekrar)\n"
                    + " - Calf Raise (4 set 8-10 tekrar)\n"
                    + " - Hanging Leg Raise (2 set 10-15 tekrar)";
        }
        case "Tüm vücut" -> {
            message = "\n\n Tüm Vücut Günü\n\n"
                    + " - Bench press (4 set 10 tekrar)\n"
                    + " - Lat pulldown (4 set 8 tekrar)\n"
                    + " - Squat (4 set 10 tekrar)\n"
                    + " - Leg curl (3 set 10-15 tekrar)\n"
                    + " - Dumbbell shoulder press (4 set 10 tekrar)\n"
                    + " - Incline curl (3 set 10 tekrar)\n"
                    + " - Rope Pushdown (3 set 12 tekrar)";
        }
        case "Boş" -> {
            message = "";
        }
        default -> {
            message = "Değişken ile eşleşme bulunamadı.";
            System.out.println(message);
        }
    }

    return message.replaceAll("\n", "\r\n");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
