
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author omera
 */
public class sekretereslestır extends javax.swing.JFrame {
    public sekretereslestır() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        mtc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        antrenor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combosaat = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        dersadıtext = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 255, 255));
        kGradientPanel1.setkGradientFocus(150);
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 153, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Müşteri T.C'si");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 100, 28));

        mtc.setBackground(new Color(0,0,0,0));
        mtc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        mtc.setOpaque(false);
        kGradientPanel1.add(mtc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 134, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setText("İşlemi Tamamla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, 31));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ders Adı");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 250, 63, 28));

        antrenor.setBackground(new Color(0,0,0,0));
        antrenor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        antrenor.setOpaque(false);
        antrenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antrenorActionPerformed(evt);
            }
        });
        kGradientPanel1.add(antrenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 134, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Saatler");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 320, 54, 27));

        combosaat.setBackground(new Color(0,0,0,0));
        combosaat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09.00", "11.00", "13.00", "15.00", "17.00", "19.00", "21.00" }));
        combosaat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        combosaat.setOpaque(false);
        kGradientPanel1.add(combosaat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 359, 137, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Müşteri-Antrenör Eşleştirme");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        dersadıtext.setBackground(new Color(0,0,0,0));
        dersadıtext.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        dersadıtext.setOpaque(false);
        dersadıtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dersadıtextActionPerformed(evt);
            }
        });
        kGradientPanel1.add(dersadıtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 290, 134, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Antrenör");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean checkMusteri(String tc){
        try {
            java.sql.Connection con = DriverManager.getConnection(
                    "jdbc:mysql://aws.connect.psdb.cloud/mmooodatabase?sslMode=VERIFY_IDENTITY",
                    "enq8p0j5ciweyw1gsfrg",
                    "pscale_pw_2QyPbaQViAG5k6JgsBdbvKXkBkeGi6h8OKgMWImpieg");
            
            String sql1 = "SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END AS result FROM Musteri WHERE TC = '" + tc + "'";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql1);
            rs.next();
            int result = rs.getInt("result");
            con.close();
            rs.close();
            if (result==1) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Musteri mevcut değil");
                return false;
            }
            
        } catch (SQLException e) {
            Logger.getLogger(sekretereslestır.class.getName()).log(Level.SEVERE, null, e);
        }
        return false;
    }
    
    public boolean checkAntrenor(String antr){
        try {
            java.sql.Connection con = DriverManager.getConnection(
                    "jdbc:mysql://aws.connect.psdb.cloud/mmooodatabase?sslMode=VERIFY_IDENTITY",
                    "enq8p0j5ciweyw1gsfrg",
                    "pscale_pw_2QyPbaQViAG5k6JgsBdbvKXkBkeGi6h8OKgMWImpieg");
            
            String sql1 = "SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END AS result FROM Personel WHERE isim = '" + antr + "'";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql1);
            rs.next();
            int result = rs.getInt("result");
            rs.close();
            con.close();
            if (result==1) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Antrenor mevcut değil");
                return false;
            }
        } catch (SQLException e) {
            Logger.getLogger(sekretereslestır.class.getName()).log(Level.SEVERE, null, e);
        }
        return false;
    
    }
    
    public boolean checkDersMevcut(String dersAdi, int saat){
        try {
            java.sql.Connection con = DriverManager.getConnection(
                    "jdbc:mysql://aws.connect.psdb.cloud/mmooodatabase?sslMode=VERIFY_IDENTITY",
                    "enq8p0j5ciweyw1gsfrg",
                    "pscale_pw_2QyPbaQViAG5k6JgsBdbvKXkBkeGi6h8OKgMWImpieg");
            
            String sql1 = "SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END AS result FROM dersEslestirme WHERE verdigiDers = '" + dersAdi + "' AND dersSaati = '" + saat + "'";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql1);
            rs.next();
            int result = rs.getInt("result");
            rs.close();
            con.close();
            if (result==1) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Antrenorun dersi mevcut değil");
                return false;
            }
        } catch (SQLException e) {
            Logger.getLogger(sekretereslestır.class.getName()).log(Level.SEVERE, null, e);
        }
        return false;
    }
    
    public void addODMADatabase(String tc, String antr, String dersAdi, int saat){
        try {
                Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex);
                System.out.println("hata");
        }
        try {
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://aws.connect.psdb.cloud/mmooodatabase?sslMode=VERIFY_IDENTITY",
                    "enq8p0j5ciweyw1gsfrg",
                    "pscale_pw_2QyPbaQViAG5k6JgsBdbvKXkBkeGi6h8OKgMWImpieg");
                
            String sql = "INSERT INTO ozelDersMuAn (antrenorName, dersName, musteriTC, dersSaati) VALUES ('"+ antr + "', '" + dersAdi + "', '" + tc + "', '" + saat + "')";
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            
            sql = "SELECT ogrenciSayisi FROM dersEslestirme WHERE verdigiDers = ?";
            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1, dersAdi);
            ResultSet resultSet = statement.executeQuery();
            if (resultSet.next()) {
                int ogrenciSayisi = resultSet.getInt("ogrenciSayisi") + 1;
                sql = "UPDATE dersEslestirme SET ogrenciSayisi = " + ogrenciSayisi + " WHERE verdigiDers = '" + dersAdi + "' AND dersSaati = '" + saat + "'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Özel ders eklendi");
                
            }else{
                JOptionPane.showMessageDialog(null, "Hata olustu");
            }
            con.close();
            resultSet.close();
        } catch (SQLException ex) {
            Logger.getLogger(sekreterMusteriEkle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tc = mtc.getText();    
        if(!checkMusteri(tc))
            return;
        
        String antr = antrenor.getText();
        if(!checkAntrenor(antr))
            return;
        
        String dersAdi = dersadıtext.getText();
        int saatIndex = combosaat.getSelectedIndex();
        switch (saatIndex) {
            case 0 -> saatIndex = 9;
            case 1 -> saatIndex = 11;
            case 2 -> saatIndex = 13;
            case 3 -> saatIndex = 15;
            case 4 -> saatIndex = 17;
            case 5 -> saatIndex = 19;
            case 6 -> saatIndex = 21;
            default -> {
            }
        }
        if(!checkDersMevcut(dersAdi, saatIndex))
            return;
        
        addODMADatabase(tc, antr, dersAdi, saatIndex);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void antrenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antrenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_antrenorActionPerformed

    private void dersadıtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dersadıtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dersadıtextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sekretereslestır.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sekretereslestır.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sekretereslestır.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sekretereslestır.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sekretereslestır().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField antrenor;
    private javax.swing.JComboBox<String> combosaat;
    private javax.swing.JTextField dersadıtext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField mtc;
    // End of variables declaration//GEN-END:variables
}
